version: "3.3"

services:
  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    # constainer_name: revive-adserver-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: revive_adserver_530
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  memcached:
    image: memcached:alpine3.14
    # constainer_name: revive-adserver-memcached
    ports:
      - 11211:11211
    restart: always

  adserver:
    depends_on:
      - db
    build: ./adserver
    container_name: revive-adserver-5.3.0
    ports:
      - 8000:80
      - 443:443
    restart: always
    environment:
      REVIVE_VERSION: 5.3.0-rc1
      REVIVE_DB_HOST: db:3306
      REVIVE_DB_USER: admin
      REVIVE_DB_PASSWORD: password

volumes:
  db-data:
