version: "2.1"
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: revive5
      MYSQL_USER: revive
      MYSQL_PASSWORD: password

  memcached:
    image: memcached:1.5-alpine
    ports:
      - "11211:11211"
    restart: always

  revive:
    depends_on:
      - db
    build: ./docker
    container_name: revive-adserver-5.3.0
    ports:
      - "8000:80"
      - "443:443"
    restart: always
    environment:
      REVIVE_VERSION: 5.3.0-rc1
      revive_DB_HOST: db:3306
      revive_DB_USER: revive
      revive_DB_PASSWORD: password
volumes:
  db_data:
